In [11]:
import numpy as np
import sys
np_arr = np.array([1,2,3,5,6])
print(np_arr)

[1 2 3 5 6]


In [5]:
# slicing
print(np_arr[1:3:])

[2 3]


In [7]:
# selective multi indexing
print(np_arr[[3,4,4]]) # note that the it is possible to pass a list of indices and extract out the element !!! the result is a numpy array

[5 6 6]


In [14]:
# forcing numpy to use a specific data type while storing the array instead of defaulting to what 
np_arr = np.array([8,7,4,3,2,4], dtype=np.int8)
prn

[8 7 4 3 2 4]
int8


In [26]:
# indexing and slicing of matrix
# let's create a multi - dimentional array
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A.ndim)

2


In [32]:
# first element of the second row
# second row
print(A[1])
# first element
print(A[1][0])

[4 5 6]
4


In [39]:
# dimension can be directly passed
print(A[1,0])
# note that what is getting passed is a slicing filter

# example
# I want first column of all rows
print(A[:, 0:1:1])

# I want last 2 elements of the second row
print(A[1:2:1, 1::])

# I want 2nd element from row and last elements from row
print(A[::, 1::1])

4
[[1]
 [4]]
[[5 6]]
[[2 3]
 [5 6]]


Start from here - https://youtu.be/r-uOLxNrNk8?list=LLgVR1SyyjIHjApjgic1zD4A&t=5999